Name:           sm-cli
Version:        0.18.0
Release:        5%{?dist}
Summary:        CLI for xapi toolstack storage managers
License:        LGPL
URL:            https://github.com/xapi-project/sm-cli
Source0:        https://code.citrite.net/rest/archive/latest/projects/XSU/repos/%{name}/archive?at=v%{version}&format=tar.gz&prefix=%{name}-%{version}#/%{name}-%{version}.tar.gz
Provides: gitsha(https://code.citrite.net/rest/archive/latest/projects/XSU/repos/sm-cli/archive?at=v0.18.0&format=tar.gz&prefix=sm-cli-0.18.0#/sm-cli-0.18.0.tar.gz) = 59a97a66041c73eb6225a01a15c8f9ae54d0f496

BuildRequires:  ocaml
BuildRequires:  opam
BuildRequires:  xs-opam-repo
BuildRequires:  ocaml-xcp-idl-devel

%description
Command-line interface for xapi toolstack storage managers.

%prep
%autosetup -p1

%build
make

%install
mkdir -p %{buildroot}/%{_sbindir}
install _build/install/default/bin/sm-cli %{buildroot}/%{_sbindir}/sm-cli


%files
%doc README.md LICENSE MAINTAINERS
%{_sbindir}/sm-cli

%changelog
* Thu May 24 2018 Christian Lindig <christian.lindig@citrix.com> - 0.18.0-1
- main: make safe-string compliant

* Tue Feb 13 2018 Christian Lindig <christian.lindig@citrix.com> - 0.17.0-1
- Update project URL to xapi-project github

* Fri Feb 09 2018 Christian Lindig <christian.lindig@citrix.com> - 0.16.0-1
- CP-24350: plumb through sharable flag

* Wed Jan 10 2018 Konstantina Chremmou <konstantina.chremmou@citrix.com> - 0.15.0-1
- Ported build from oasis to jbuilder

* Fri Oct 13 2017 Rob Hoes <rob.hoes@citrix.com> - 0.14.0-1
- Rename VDI.export_changed_blocks to VDI.list_changed_blocks
- Add new cbt_enabled vdi_info param to vdi_create command

* Fri Aug 11 2017 Rob Hoes <rob.hoes@citrix.com> - 0.13.0-1
- Add VDI.data_destroy call to CLI
- Add VDI.export_changed_blocks call to the CLI

* Mon Jul 03 2017 Rob Hoes <rob.hoes@citrix.com> - 0.12.0-1
- Add VDI.enable_cbt call to CLI
- Add VDI.disable_cbt call to CLI

* Fri May 12 2017 Rob Hoes <rob.hoes@citrix.com> - 0.11.0-1
- Update to newest storage interface
- Remove Makefile generated by DevFiles OASIS plugin

* Mon Mar 13 2017 Marcello Seri <marcello.seri@citrix.com> - 0.10.0-2
- Update OCaml dependencies and build/install script after xs-opam-repo split

* Thu Mar 02 2017 Gabor Igloi <gabor.igloi@citrix.com> - 0.10.0-1
- Port to xs-opam-repo providing updated OCaml libraries:
  switch to newer ppx-based rpc library
- Port to OASIS
- Download source from mirror

* Wed Sep 9 2015 David Scott <dave.scott@citrix.com> - 0.9.7-1
- Update to 0.9.7

* Fri Aug 14 2015 David Scott <dave.scott@citrix.com> - 0.9.5-1
- Update to 0.9.5

* Fri Oct 25 2013 David Scott <dave.scott@eu.citrix.com> - 0.9.4-1
- Update to 0.9.4

* Thu May 30 2013 David Scott <dave.scott@eu.citrix.com>
- Initial package

