%global package_speccommit 991f5c71b0207c29254f4415c1500db0f58b1adb
%global package_srccommit v0.23.0
Name:           sm-cli
Version: 0.23.0
Release: 53.1%{?xsrel}%{?dist}
Summary:        CLI for xapi toolstack storage managers
License:        LGPL-2.1-or-later WITH OCaml-LGPL-linking-exception
URL:            https://github.com/xapi-project/sm-cli
Source0: sm-cli-0.23.0.tar.gz

BuildRequires:  ocaml
BuildRequires:  opam
BuildRequires:  xs-opam-repo
BuildRequires:  ocaml-xcp-idl-devel

%description
Command-line interface for xapi toolstack storage managers.

%prep
%autosetup -p1

%build
make

%install
mkdir -p %{buildroot}/%{_sbindir}
install _build/install/default/bin/sm-cli %{buildroot}/%{_sbindir}/sm-cli


%files
%doc README.md LICENSE MAINTAINERS
%{_sbindir}/sm-cli

%changelog
* Wed Aug 09 2023 Gael Duperrey <gduperrey@vates.fr> - 0.23.0-53.1
- Sync with hotfix XS82ECU1040
- *** Upstream changelog ***
- * Thu Jul 20 2023 Rob Hoes <rob.hoes@citrix.com> - 0.23.0-53
- - Bump release and rebuild
- * Mon Jun 19 2023 Christian Lindig <christian.lindig@citrix.com> - 0.23.0-52
- - Bump release and rebuild
- * Thu Jun 08 2023 Christian Lindig <christian.lindig@citrix.com> - 0.23.0-51
- - Bump release and rebuild
- * Fri May 12 2023 Christian Lindig <christian.lindig@citrix.com> - 0.23.0-50
- - Bump release and rebuild
- * Fri May 12 2023 Christian Lindig <christian.lindig@citrix.com> - 0.23.0-49
- - Bump release and rebuild
- * Thu Feb 23 2023 Pau Ruiz Safont <pau.ruizsafont@cloud.com> - 0.23.0-48
- - Change license to match source repo
- * Mon Feb 20 2023 Pau Ruiz Safont <pau.ruizsafont@cloud.com> - 0.23.0-47
- - Bump package to avoid reusing versions from other versions

* Wed Aug 17 2022 Gael Duperrey <gduperrey@vates.fr> - 0.23.0-7
- Rebuild for updated ocaml-xcp-idl from XS82ECU1011

* Mon Sep 27 2021 Pau Ruiz Safont <pau.safont@citrix.com> - 0.23.0-6
- Bump package after xs-opam update

* Tue Jul 13 2021 Edwin Török <edvin.torok@citrix.com> - 0.23.0-5
- bump packages after xs-opam update

* Fri Aug 23 2019 Edwin Török <edvin.torok@citrix.com> - 0.23.0-3
- bump packages after xs-opam update

* Tue Dec 04 2018 Christian Lindig <christian.lindig@citrix.com> - 0.23.0-1
- Moved from jbuilder to dune and deprecated xcp in favour of xapi-idl.

* Thu Nov 01 2018 Christian Lindig <christian.lindig@citrix.com> - 0.22.0-1
- Update opam for Opam 2, trim dependencies in opam file

* Mon Oct 22 2018 Christian Lindig <christian.lindig@citrix.com> - 0.21.0-1
- Fix Travis

* Mon Sep 24 2018 Christian Lindig <christian.lindig@citrix.com> - 0.20.0-1
- CP-27110: Convert to PPX storage interface
- CP-27110: Reinstate sharable flag

* Fri Aug 31 2018 Christian Lindig <christian.lindig@citrix.com> - 0.19.0-1
- Simplify PPX processing in jbuild file
- Update .travis.yml to use ocaml-ci-scripts

* Thu May 24 2018 Christian Lindig <christian.lindig@citrix.com> - 0.18.0-1
- main: make safe-string compliant

* Tue Feb 13 2018 Christian Lindig <christian.lindig@citrix.com> - 0.17.0-1
- Update project URL to xapi-project github

* Fri Feb 09 2018 Christian Lindig <christian.lindig@citrix.com> - 0.16.0-1
- CP-24350: plumb through sharable flag

* Wed Jan 10 2018 Konstantina Chremmou <konstantina.chremmou@citrix.com> - 0.15.0-1
- Ported build from oasis to jbuilder

* Fri Oct 13 2017 Rob Hoes <rob.hoes@citrix.com> - 0.14.0-1
- Rename VDI.export_changed_blocks to VDI.list_changed_blocks
- Add new cbt_enabled vdi_info param to vdi_create command

* Fri Aug 11 2017 Rob Hoes <rob.hoes@citrix.com> - 0.13.0-1
- Add VDI.data_destroy call to CLI
- Add VDI.export_changed_blocks call to the CLI

* Mon Jul 03 2017 Rob Hoes <rob.hoes@citrix.com> - 0.12.0-1
- Add VDI.enable_cbt call to CLI
- Add VDI.disable_cbt call to CLI

* Fri May 12 2017 Rob Hoes <rob.hoes@citrix.com> - 0.11.0-1
- Update to newest storage interface
- Remove Makefile generated by DevFiles OASIS plugin

* Mon Mar 13 2017 Marcello Seri <marcello.seri@citrix.com> - 0.10.0-2
- Update OCaml dependencies and build/install script after xs-opam-repo split

* Thu Mar 02 2017 Gabor Igloi <gabor.igloi@citrix.com> - 0.10.0-1
- Port to xs-opam-repo providing updated OCaml libraries:
  switch to newer ppx-based rpc library
- Port to OASIS
- Download source from mirror

* Wed Sep 9 2015 David Scott <dave.scott@citrix.com> - 0.9.7-1
- Update to 0.9.7

* Fri Aug 14 2015 David Scott <dave.scott@citrix.com> - 0.9.5-1
- Update to 0.9.5

* Fri Oct 25 2013 David Scott <dave.scott@eu.citrix.com> - 0.9.4-1
- Update to 0.9.4

* Thu May 30 2013 David Scott <dave.scott@eu.citrix.com>
- Initial package

